import htmlPdf from 'html-pdf-node';
import type { ValuationData } from '../../client/src/lib/validations';

function generateReportHtml(data: ValuationData): string {
  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      maximumFractionDigits: 0,
      notation: 'compact'
    }).format(value);
  };

  const formatDate = () => {
    return new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  };

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Startup Valuation Report</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          line-height: 1.6;
          color: #333;
          max-width: 800px;
          margin: 0 auto;
          padding: 40px;
        }
        .header {
          text-align: center;
          margin-bottom: 40px;
          padding-bottom: 20px;
          border-bottom: 2px solid #eee;
        }
        .valuation {
          font-size: 36px;
          color: #2563eb;
          font-weight: bold;
          margin: 20px 0;
        }
        .section {
          margin: 30px 0;
        }
        .section-title {
          font-size: 20px;
          font-weight: bold;
          margin-bottom: 15px;
          color: #1f2937;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin: 15px 0;
        }
        th, td {
          padding: 12px;
          text-align: left;
          border-bottom: 1px solid #eee;
        }
        th {
          background-color: #f9fafb;
        }
        .footer {
          margin-top: 40px;
          padding-top: 20px;
          border-top: 2px solid #eee;
          font-size: 12px;
          color: #6b7280;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Startup Valuation Report</h1>
        <p>Generated on ${formatDate()}</p>
      </div>

      <div class="section">
        <div class="valuation">
          ${formatCurrency(data.valuation)}
        </div>
        <p>Estimated Company Valuation</p>
      </div>

      <div class="section">
        <div class="section-title">Valuation Summary</div>
        <table>
          <tr>
            <th>Metric</th>
            <th>Value</th>
          </tr>
          <tr>
            <td>Revenue Multiple</td>
            <td>${data.multiplier.toFixed(1)}x</td>
          </tr>
          <tr>
            <td>Base Valuation</td>
            <td>${formatCurrency(data.details.baseValuation)}</td>
          </tr>
        </table>
      </div>

      <div class="section">
        <div class="section-title">Valuation Adjustments</div>
        <table>
          <tr>
            <th>Factor</th>
            <th>Impact</th>
          </tr>
          ${Object.entries(data.details.adjustments)
            .map(([key, value]) => `
              <tr>
                <td>${key.replace(/([A-Z])/g, ' $1')}</td>
                <td style="color: ${value > 0 ? '#059669' : '#dc2626'}">
                  ${value > 0 ? '+' : ''}${formatCurrency(value)}
                </td>
              </tr>
            `).join('')}
        </table>
      </div>

      <div class="section">
        <div class="section-title">Methodology</div>
        <p>${data.methodology}</p>
      </div>

      <div class="footer">
        <p>This report was generated by StartupValuator. The valuation provided is an estimate based on the information provided and industry standards. It should not be considered as financial advice.</p>
      </div>
    </body>
    </html>
  `;
}

export async function generatePdfReport(data: ValuationData): Promise<Buffer> {
  const html = generateReportHtml(data);
  const options = {
    format: 'A4',
    margin: { top: 20, right: 20, bottom: 20, left: 20 },
    printBackground: true
  };

  return new Promise((resolve, reject) => {
    htmlPdf.generatePdf({ content: html }, options)
      .then(pdfBuffer => resolve(pdfBuffer))
      .catch(error => reject(error));
  });
}
